---
# tasks file for roles/ftp_client

- name: Create ftpusers group
  group:
    name: ftpusers
    state: present

- name: Add users that are allowed to use the FTP Server
  user:
    name: "{{ name }}"
    state: "{{ state }}"
    comment: "{{ comment }}"
    home: "/home/{{ name }}"
    shell: "/bin/false"
    password: "{{ password }}"
    groups: ftpusers
    update_password: always

