---  

- name: Install and configure vsftpd server
  hosts: target
  vars:
    ftp_server_banner: "Welcome to the FTP service"

  tasks:
  - name: Include variables from config.yaml
    include_vars:
      file: config.yaml

  - name: Install ftp server
    include_role:
      name: ftp-server


  - name: ftp user testing
    include_role:
      name: ftp_client
